version: '2'
services:
  mamiferos2020-app:
    image: mamiferos2020
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://mamiferos2020-mysql:3306/mamiferos2020?useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  mamiferos2020-mysql:
    extends:
      file: mysql.yml
      service: mamiferos2020-mysql
